seed: 42
token_length: 128
epochs: 1
batch_size: 32
lr: !!float 5e-6
weight_decay: 0.01
data_fraction: 1.0
val_percentage: 0.2
fraction_layers_to_finetune: 0.0
classification_head_hidden_dim: 64
classification_head_dropout_rate: 0.2
classification_head_hidden_layers: 4
output_path: "results"
data_path: "data"
